version: 0.0
os: linux

files:
  - source: /automation/discord-bot/CD/"  
    destination: /home/ec2-user/
    overwrite: yes
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: ec2-user
