version : '3.7'

services:
    redis_container_1:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis
      ports:
        - 6379:6379

    spring_main_server:
      image : ${REPO_URL}
      command: java -jar ./sms-infrastructure/build/libs/sms-infrastructure-0.0.1-SNAPSHOT.jar
      ports:
        - 8080:8080
      volumes:
      - .:/app
      depends_on:
      - redis_container_1 