#discodbot.yml
name: sms-discodbot-pipeline
on:
  push:
    paths:
      - "automation/discord-bot/CD/**"  
    branches: [ main ]

env:
  token: ${{ secrets.DISCORD_BOT_TOKEN }}
  channel: ${{ secrets.ANDROID_CHANNEL }}

permissions:
  contents: read

jobs:
  discord_bot:
    name: 'Discord_bot'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Create .env
      run: |
        touch ./automation/discord-bot/CD/.env
        echo "${{ secrets.NYOPA_ENV }}" > ./automation/discord-bot/CD/.env
      shell: bash

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }} -f ./automation/discord-bot/CD/Dockerfile .
        docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.REPO_URL }}:$IMAGE_TAG
        docker push ${{ secrets.REPO_URL }}:$IMAGE_TAG

          
    - name: SMS-Backend-CD Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ SMS-DiscordBot-CD 성공! ✅
        webhook: ${{ secrets.SMS_DISCORD_CD_WEBHOOK }}
        color: 00FF00

    - name: SMS-Backend-CD Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️ SMS-DiscordBot-CD 실패! ❗️
        webhook: ${{ secrets.SMS_DISCORD_CD_WEBHOOK }}
        color: FF0000
