name: fitcloud fee crawler

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  send:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./automation/discord-bot/fee-bot/requirements.txt
      - name: Create .env
        run: |
          touch ./automation/discord-bot/fee-bot/.env
          echo "${{ secrets.FEE_ENV }}" > ./automation/discord-bot/fee-bot/.env
      - name: run webhook
        run: |
          python ./automation/discord-bot/fee-bot/webhook-fitcloud-crawl-data.py
