# terraform.yaml
name: sms-devops-trraform-pipeline
on:
  push:
    branches: [ "main" ]


env:
  AWS_REGION: ap-northeast-2

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      
    - name : Create provider.tf
      run : |
        touch terraform/provider.tf
        echo  "${{ secrets.TERRAFORM_PROVIDER }}" > terraform/provider.tf
      shell: bash
      
    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -input=false

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply
