# terraform.yaml
name: sms-devops-trraform-pipeline
on:
  push:
    branches: [ "main" ]


env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  code_pipeline_bucekt: ${{ secrets.CODE_PIPELINE_BUCKET }}
  db_password: ${{ secrets.DB_PASSWORD }}
  user_name: ${{ secrets.USER_NAME }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        export TF_VAR_db_password="${{ env.db_password }}"
        export TF_VAR_code_pipeline_bucekt="${{ env.code_pipeline_bucekt }}"
        export TF_VAR_user_name="${{ env.user_name }}"
        terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        export TF_VAR_db_password="${{ env.db_password }}"
        export TF_VAR_code_pipeline_bucekt="${{ env.code_pipeline_bucekt }}"
        export TF_VAR_user_name="${{ env.user_name }}"
        terraform apply -input=false

